version: '3.1'

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql-container
    env_file:
      - '.env'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - api_network

  api:
    build: .
    image: django-docker-image
    container_name: django-docker-container
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    networks:
      - api_network
    depends_on:
      - mysql_db

networks:
  api_network:
    driver: bridge