version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    env_file:
      - './lib_management/.env'
    environment:
      MYSQL_ROOT_PASSWORD: 2431999
      MYSQL_USER: api_user
      MYSQL_PASSWORD: 2431999
      MYSQL_DATABASE: mysql_db
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data-volume:/var/lib/mysql
    networks:
      - api_network

  api:
    build: .
    image: django-docker-image
    container_name: django-docker-container
    restart: unless-stopped
    env_file:
      - './lib_management/.env'
    ports:
      - "8080:8000"
    networks:
      - api_network
    depends_on:
      - db

networks:
  api_network:
    driver: bridge